name: Development Branch Deployment

on:
  push:
    branches: [dev]
    paths-ignore:
      - "README.md"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Archive application build
        run: |
          mkdir app
          cp -r alembic api qa_tests scripts tests requirements.txt alembic.ini app/
          cp *.py app/
          tar -czf python-dev.tar.gz app

      - name: Copy Artifacts to server
        run: |
          sshpass -p ${{ secrets.PASSWORD }} scp -o StrictHostKeyChecking=no python-dev.tar.gz ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/tmp/python
          rm -f python-dev.tar.gz

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd boilerplate/python/dev
            tar -xzf /tmp/python/python-dev.tar.gz -C .
            rm -f /tmp/python/python-dev.tar.gz
            cp .env app/.env
            source venv/bin/activate
            cd app
            pip install -r requirements.txt
            alembic upgrade head
            cd ..
            pm2 restart dev-ecosystem.config.js || pm2 start dev-ecosystem.config.js
